# Generated by Django 3.2.4 on 2021-07-11 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=30)),
                ('application_description', models.TextField(blank=True, default='', max_length=400)),
                ('application_picture_url', models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
            ],
        ),
    ]
