# Generated by Django 3.2.4 on 2021-07-15 00:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=30)),
                ('contents_url', models.TextField(max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('icon_image_path', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^./[/.*/]*.+.[png|jpg]$')])),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
        ),
    ]
