# Generated by Django 3.2.4 on 2021-07-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_workoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoption',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_options', to='works.work'),
        ),
    ]
