# Generated by Django 3.2.4 on 2021-07-26 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_workoption_icon_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='application_picture_url',
            field=models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator('^\\./[/.*/]*.+\\.png|jpg$')]),
        ),
    ]
