# Generated by Django 3.2.4 on 2021-07-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillLabel', models.CharField(max_length=200)),
                ('skilledStars', models.IntegerField(default=1)),
                ('skillType', models.CharField(max_length=20)),
            ],
        ),
    ]
