# Generated by Django 3.2.4 on 2021-07-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skillLabel',
            new_name='skill_label',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skillType',
            new_name='skill_type',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skilledStars',
            new_name='skilled_stars',
        ),
    ]
